modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "Unlicense"

[[mods]]
modId = "levels"
version = "${version}"
displayName = "Levels"
authors = ""
description = '''

'''
#logoFile = ""

[[dependencies.levels]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.levels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.levels]]
modId = "architectury"
mandatory = true
versionRange = "[1.32.68,)"
ordering = "AFTER"
side = "BOTH"
