modLoader = "javafml"
loaderVersion = "[36,)"
#issueTrackerURL = ""
license = "GPLv2"

[[mods]]
modId = "levels"
version = "${version}"
displayName = "Levels"
authors = "Vaan1310,TheXFactor117"
description = '''

'''
logoFile = "/assets/levels/logo/icon.png"

[[dependencies.levels]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.levels]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.levels]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
